"""Add admin features: next_meeting_date to chamas, meeting_minutes and chama_announcements tables

Revision ID: 207e2b37d538
Revises: 63302c213eaf
Create Date: 2025-07-09 23:49:11.853538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207e2b37d538'
down_revision = '63302c213eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chama_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('announcement_type', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('target_members', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_minutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('secretary_id', sa.Integer(), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('meeting_title', sa.String(length=200), nullable=False),
    sa.Column('attendees', sa.JSON(), nullable=True),
    sa.Column('agenda_items', sa.JSON(), nullable=True),
    sa.Column('decisions_made', sa.Text(), nullable=True),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('minutes_content', sa.Text(), nullable=True),
    sa.Column('attachment_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['secretary_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chamas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_meeting_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_id', sa.Integer(), nullable=True))

    # Commented out: subscription_plan_pricing table doesn't exist
    # with op.batch_alter_table('subscription_payments', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'subscription_plan_pricing', ['pricing_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Commented out: subscription_plan_pricing table doesn't exist
    # with op.batch_alter_table('subscription_payments', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('related_id')

    with op.batch_alter_table('chamas', schema=None) as batch_op:
        batch_op.drop_column('next_meeting_date')

    op.drop_table('meeting_minutes')
    op.drop_table('chama_announcements')
    # ### end Alembic commands ###
